# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ReadWriteLock"); Pkg.test("ReadWriteLock"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ReadWriteLock")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
